### ISSUE TITLE
`This version of the MoonBoard app is now obsolete, please download the new MoonBoard app from the store.` error

### ISSUE THREAD

**Issue by ngmy** [spookykat/MoonBoard#6]
Thanks for creating such useful software!

Since the recent release of the new official MoonBoard app, `fetch_problems.py` has stopped working.

The following is the error displayed:
```console
$ python3 fetch_problems.py
Traceback (most recent call last):
  File "fetch_problems.py", line 58, in <module>
    json_data = requestProblemsJson(0, z, holdset, angle)
  File "fetch_problems.py", line 14, in requestProblemsJson
    'authorization': f'BEARER {getAccessToken()}',
  File "/home/nagamiya/tmp/MoonBoard/get_accesstoken.py", line 15, in getAccessToken
    'refresh_token': getRefreshToken(),
  File "/home/nagamiya/tmp/MoonBoard/get_accesstoken.py", line 39, in getRefreshToken
    return(r.json()['refresh_token'])
KeyError: 'refresh_token'
```

I wrote a `print` statement to `get_accesstoken.py` and the MoonBoard server returned the following response:
```json
{'error': 'Obsolete', 'error_description': 'This version of the MoonBoard app is now obsolete, please download the new MoonBoard app from the store.'}
```
```diff
diff --git a/get_accesstoken.py b/get_accesstoken.py
index 27cfd11..ed7b06f 100644
--- a/get_accesstoken.py
+++ b/get_accesstoken.py
@@ -36,4 +36,5 @@ def getRefreshToken():
         'client_id': 'com.moonclimbing.mb'
     }
     r = requests.get(URL, headers=headers, data=data)
+    print(r.json())
     return(r.json()['refresh_token'])
```

Are there any plans to release a new version of the software that will resolve this issue?

**Comment by JuliaSchoepp** [comment]
The same has happened to me. If anyone could share an old snapshot of the problems, I'd be interested in that as well, as I only want to play around with the data a litte. Thanks in advance

**Comment by musoke** [comment]
[problems_2023_01_30.zip](https://github.com/spookykat/MoonBoard/files/13193317/problems_2023_01_30.zip)

**Comment by rawtaz** [comment]
It's truly amazing how the Moon folks go to lengths with making the information, that their paying users produce for them to make the Moonboard ecosystem such a contentful one, inaccessible.

Their Android app doesn't seem to work without Google Play services either, so not only do they make it difficult to access the data without their app.

Such a shame, would be nice if they were more transparent and opened up usage 👎

**Comment by gordoste** [comment]
@musoke Massive thanks for sharing that file. I have a DIY LED system and was using the 2016 hold setup. I am looking at moving to a new hold setup but was thinking I would need to manually enter the problems one by one!

**Comment by jere357** [comment]
thx for this, i was trying to emulate the moonboard app in order to scrape this data, but i couldnt even get the app to open in the emulator -.-

**Comment by Aralox** [comment]
Has anyone made any progress on obtaining up-to-date moon climb data? I'm (vibe-)training a neural network to help generate home spray wall routes. I've incorporated the 300-400k kilter routes available, and would like to use moon routes for training too.

**Comment by gordoste** [comment]
There is a better option for DIY LED systems now - https://github.com/FabianRig/ArduinoMoonBoardLED
This lets you use the Moon app to control a DIY LED system. It's limited too a specific Arduino model (Arduino Nano 33 BLE). I made the same thing using the Zephyr framework (https://github.com/gordoste/zboard), which makes it very easy to port to other boards.

**Comment by Aralox** [comment]
Thanks, I've got something custom written for my setup to control LEDs, and I was aided by that when I was working on it. I also use a custom app for managing routes instead of the moon app. But that's another topic - I'm specifically looking for the moon dataset for ML training work. Cheers

**Comment by fallaciousreasoning** [comment]
I've got a dump of the 2024 Benchmarks (at 40 degrees) here:

[Benchmark Problems Moonboard 2024 40.json](https://github.com/user-attachments/files/29187719/Benchmark.Problems.Moonboard.2024.40.json)

working on getting the rest

**Comment by fallaciousreasoning** [comment]
Full list of Moonboard 2024 Problems at 40 degrees (as of 2026-06-24) https://gist.github.com/fallaciousreasoning/9f1db3459bf9e5c0f558f35e56adcc9a

**Comment by Aralox** [comment]
Hi mate I think that the repo is on private

**Comment by fallaciousreasoning** [comment]
Whoops - fixed. Had it as private while I was still scraping

**Comment by fallaciousreasoning** [comment]
Moonboard Mini 2025 @ 40 degrees dump (2026-06-25):
https://gist.github.com/fallaciousreasoning/e39fd062b7fe59f586318543e40a68a4

**Comment by fallaciousreasoning** [comment]
Moonboard Mini 2020 @ 40 degrees dump (2026-06-25):
https://gist.github.com/fallaciousreasoning/f18a56a47487124d52fb1b2e929e7f99

**Comment by fallaciousreasoning** [comment]
Moonboard 2019 @ 40 degrees dump (2026-06-25):
https://gist.github.com/fallaciousreasoning/29e1b1662ba868d896dbee3c11767b08

**Comment by fallaciousreasoning** [comment]
More (and better) data from the new Moonboard app:

[Mini MoonBoard 2020.zip](https://github.com/user-attachments/files/29364112/Mini.MoonBoard.2020.zip)
[Mini MoonBoard 2025.zip](https://github.com/user-attachments/files/29364113/Mini.MoonBoard.2025.zip)
[MoonBoard 2010.zip](https://github.com/user-attachments/files/29364115/MoonBoard.2010.zip)
[MoonBoard 2016.zip](https://github.com/user-attachments/files/29364117/MoonBoard.2016.zip)
[MoonBoard 2024.zip](https://github.com/user-attachments/files/29364114/MoonBoard.2024.zip)
[MoonBoard Masters 2017.zip](https://github.com/user-attachments/files/29364118/MoonBoard.Masters.2017.zip)
[MoonBoard Masters 2019.zip](https://github.com/user-attachments/files/29364116/MoonBoard.Masters.2019.zip)

**Comment by rerime** [comment]
@fallaciousreasoning how you get data from new app?

**Comment by fallaciousreasoning** [comment]
There was a brief moment where you could extract it from the app. Apart from that I was scraping data out of screenshots (which is pretty slow)
